import { revenueRows } from "../../data/sampleDatabase";
import { revenueSummaryTransform, revenueTableTransform } from "../../data/transforms";
import type { CanvasNode } from "../../artifacts/types";

export const initialNodes: CanvasNode[] = [
  {
    id: "node-revenue",
    artifactId: "metric-card",
    title: "Revenue Summary",
    x: 80,
    y: 90,
    width: 280,
    height: 170,
    zIndex: 2,
    data: revenueSummaryTransform.apply(revenueRows),
    dataBinding: {
      sourceId: "sample-revenue",
      transformId: revenueSummaryTransform.id,
    },
    config: {},
  },
  {
    id: "node-probability",
    artifactId: "inflection-probability",
    title: "Renewable Supply Model",
    x: 410,
    y: 80,
    width: 720,
    height: 460,
    zIndex: 1,
    data: {
      title: "Renewable supply-demand probability",
      note: {
        what: "Probability that renewable power supply growth outpaces demand by quarter.",
        read: "Bars show the quarterly shift probability; the line shows cumulative probability.",
        logic: "Requires generation above demand, reserve recovery, and new capacity online.",
      },
      points: [
        { quarter: "2026Q2", probabilityAt: 0, probabilityBy: 0 },
        { quarter: "2026Q3", probabilityAt: 0, probabilityBy: 0 },
        { quarter: "2026Q4", probabilityAt: 0, probabilityBy: 0 },
        { quarter: "2027Q1", probabilityAt: 0, probabilityBy: 0.002 },
        { quarter: "2027Q2", probabilityAt: 0.004, probabilityBy: 0.006 },
        { quarter: "2027Q3", probabilityAt: 0.014, probabilityBy: 0.016 },
        { quarter: "2027Q4", probabilityAt: 0.032, probabilityBy: 0.046 },
        { quarter: "2028Q1", probabilityAt: 0.052, probabilityBy: 0.094 },
        { quarter: "2028Q2", probabilityAt: 0.046, probabilityBy: 0.138 },
        { quarter: "2028Q3", probabilityAt: 0.073, probabilityBy: 0.202 },
        { quarter: "2028Q4", probabilityAt: 0.116, probabilityBy: 0.294 },
        { quarter: "2029Q1", probabilityAt: 0.136, probabilityBy: 0.386 },
        { quarter: "2029Q2", probabilityAt: 0.247, probabilityBy: 0.538 },
        { quarter: "2029Q3", probabilityAt: 0.252, probabilityBy: 0.654 },
      ],
      markers: {
        p25: "2028Q4",
        p50: "2029Q2",
        p75: "2030Q1",
      },
    },
    config: {},
  },
  {
    id: "node-flow",
    artifactId: "flow-diagram",
    title: "Artifact Pipeline",
    x: 190,
    y: 610,
    width: 560,
    height: 300,
    zIndex: 1,
    data: {
      title: "Database rows to generated artifact",
      summary: "AI output stays inside the registry contract.",
      steps: [
        { label: "Query", detail: "6 revenue rows", metric: "raw" },
        { label: "Transform", detail: "normalize fields", metric: "typed" },
        { label: "Render", detail: "React artifact", metric: "live" },
      ],
    },
    config: {},
  },
  {
    id: "node-sankey",
    artifactId: "sankey-flow",
    title: "Allocation Sankey",
    x: 840,
    y: 610,
    width: 600,
    height: 360,
    zIndex: 2,
    data: {
      title: "Supply allocation flow",
      subtitle: "Available generation moves through storage and grid balancing into regional demand.",
      nodes: [
        { name: "Solar" },
        { name: "Wind" },
        { name: "Storage" },
        { name: "Grid" },
        { name: "North" },
        { name: "South" },
      ],
      links: [
        { source: "Solar", target: "Storage", value: 42 },
        { source: "Solar", target: "Grid", value: 18 },
        { source: "Wind", target: "Storage", value: 20 },
        { source: "Wind", target: "Grid", value: 34 },
        { source: "Storage", target: "North", value: 38 },
        { source: "Storage", target: "South", value: 24 },
        { source: "Grid", target: "North", value: 28 },
        { source: "Grid", target: "South", value: 24 },
      ],
    },
    config: {},
  },
  {
    id: "node-table",
    artifactId: "table-preview",
    title: "Database Rows",
    x: 80,
    y: 310,
    width: 430,
    height: 260,
    zIndex: 3,
    dataBinding: {
      sourceId: "sample-revenue",
      transformId: revenueTableTransform.id,
    },
    data: revenueTableTransform.apply(revenueRows),
    config: {},
  },
];
